<?php

function webform_gmap_webform_component_info() {
  return array(
    'gmap' => array(
      'label' => t('Map location'),
      'description' => t('Set latitude and longitude by picking it from gmap.'),
      'file' => 'gmap.inc',
      'features' => array(
      ),
    ),
  );
}


/**
 * Implements hook_elements().
 */
function webform_gmap_elements() {
  // A few of our components need to be defined here because Drupal does not
  // provide these components natively. Because this hook fires on every page
  // load (even on non-webform pages), we don't put this in the component .inc
  // files because of the unnecessary loading that it would require.
  $elements['webform_gmap'] = array('#input' => 'TRUE');
  return $elements;
}

